apiVersion: v1
kind: Service
metadata:
  name: spring-boot-ticketing
spec:
  selector:
    app: spring-boot-ticketing
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080


